rgommezz/react-native-offline

README.md

In a usage example, there was a missing / in View closing tag
I've put it back where it belongs! ;)
Have a nice day!

Added missing / in README example

---

package.json
src/ConnectivityRenderer.js
src/withNetworkConnectivity.js
yarn.lock

Hello,
I recent versions of react, the PropTypes property was removed, and this module stopped working (I was interested in withNetworkConnectivity for example).
Would you mind releasing a version with this change which uses the external 'prop-types' package as source for PropTypes ?

Use PropTypes from prop-types package instead of React.PropTypes

---

README.md
src/checkConnectivityInterval.js
src/checkInternetAccess.js
src/withNetworkConnectivity.js

Hi there @rauliyohmc !
Thanks for the awesome lib. Super helpful.
I noticed an issue in my case, though. 
It is that is check the connectivity only at startup, so I added an option so it checks regularly for connection and by default, it keeps the exact same behaviour that you had.
What do you think ? 🙂

Added ability to check connectivity regularly

---

README.md

[Starting React-Native v0.48.4 the NetInfo's "change" event is deprecated](https://github.com/facebook/react-native/releases/tag/v0.48.4)
The new event type is 'connectionChange'

update connection type event (in the readme)

---

package.json
src/index.js
src/saga.js
yarn.lock

This pull request introduces the functionality of the `withNetworkConnectivity` component wrapper inside a saga, so there's no need to wrap any components. The same functionality now can be achieved just by including a fork from the rootSaga as below:
```javascript
yield fork(networkEventsListenerSaga)
```
As pointed out on https://github.com/rauliyohmc/react-native-offline/issues/12, if you have multiple root components (eg. by using react-native-navigation), besides having to wrap all of them, you end up having HEAD requests for each wrapped component that is mounted, which I believe it's not ideal. This solves this issue.
Additionaly, there's a `forceTryConnectivity` saga, which forces the device to test the connectivity any time. This is very useful for the situation when there's …

Creating sagas for handling connectivity changes

---

src/sagas.js

#72 
Add yield in front of select call in handleConnectivityChange function

Fixes issue where `actionQueue` was not dispatching actions on network reconnect

---

src/withNetworkConnectivity.js

When using `checkConnectionInterval` in `withNetworkConnectivity`, it pings the `pingServerUrl` every interval.
It also re-rendering every time even `isConnected` does not change at all.
To prevent re-rendering, change `React.Component` to `React.PureComponent` solved this issue.

Prevent re-rendering when using checkConnectionInterval

---

src/checkConnectivityInterval.js

Once interval is cleared, it cannot be created again. Useful when hot reloading.

Free interval variable after clearInterval()

---

src/sagas.js

I wanted to try this library to see if it works as explained or not, but I could not get it working (it was always showing isConnected = false), but after a while I realized that the pingServerUrl is using unsecured protocol (http) which IOS does not allow (it can allow with setting unsecured configurations in whole), but it is always better to be secured and use https protocol as default.  
At the mean time the fix will avoid the confusion and frustration for new users who just want to use the default config parameters of the library.
Closes https://github.com/rgommezz/react-native-offline/issues/103

default pingServerUrl  (http) protocol converted to (https) protocol

---

src/withNetworkConnectivity.js

When Redux integration is enabled by `withRedux`, `react-native-offline` only updates the Redux store but not its own state, which leads to inside/outside state inconsistencies.
This PR removes the `else` branch responsible for not updating internal state, making the library work more reliably.

fix Redux integration desynchronizing internal state

---

README.md
src/checkInternetAccess.js
src/types.js
src/withNetworkConnectivity.js

Inspired by https://github.com/rgommezz/react-native-offline/issues/74 and needed for my own project I implemented support of custom http methods _HEAD_ and _OPTIONS_ to check internet-access (only for method **withNetworkConnectivity**)
Closes #74

Add support of custom http methods "HEAD" & "OPTIONS" (only for withNetworkConnectivity)

---

src/withNetworkConnectivity.js

If using redux integration and option `checkIntervalOfflineOnly`. 
It will never make request to check internet connection. 
HOC `withNetworkConnectivity` has internal state, in which connection status is stored.
This however never gets updated. It's only set once during initialisation.
> Make sure there is no internet connection
```js
withNetworkConnectivity({
withRedux: true,
checkConnectionInterval: 3000,
checkIntervalOfflineOnly: true,
}),
```
Open app and check if there is any network request made to `google.com`. There will be no requests made. If we turn off option `checkIntervalOfflineOnly`, everything works fine.
With my change, it will always sync internal state with external redux state.

Fix issue when using redux and checkIntervalOfflineOnly

---

README.md

redux-persist is well into [V5](https://github.com/rt2zz/redux-persist/blob/master/docs/MigrationGuide-v5.md)
The `persistStore()` function is changed and the `autoRehydrate()` function is removed.
This PR updates the documentation for `configureStore()` using `redux-persist` >V5 in the README

Update redux-persist instructions

---

package.json

`react-native-offline` is compatible only with react-redux v6 per its dependency list.
In case when the project uses `react-native-offline`, `react-redux` v7, `react-native-offline` loses store in context as it uses context from `react-native-offline/node_modules/react-redux` (v6) instead of ` the_project/node_modules/react-redux` (v7).
This PR just adjusts compatible version list of `react-redux`.
[React-redux](https://github.com/reduxjs/react-redux/releases) repository says that there shouldn't be any breaking changes.
> This release should be public-API-compatible with version 6. The only public breaking change is the update of our React peer dependency from 16.4 to 16.8.4.
Closes #184

Bug: add react-redux v7 as a compatible version to avoid loosing store in context

---

README.md
__mocks__/@react-native-community/netinfo.js
package.json
src/components/NetworkConnectivity.js
src/redux/sagas.js
src/utils/checkInternetConnection.js
test/NetworkConnectivity.test.js
test/checkInternetConnection.test.js
test/sagaChannels.test.js
test/sagas.test.js
test/setupTestEnv.js
yarn.lock

Uses the newly separated `@react-native-community/netinfo` package, extracted from the core.
Fixes #172

React-native-offline v5

---

README.md

add china - google.com warning

---

README.md

I was trying the way `README.md` explain about configuration from `persistStore` but I saw in the codebase and the second parameter need to be an object and pass the storage way are being used in the project.
Read the `README.md` file i.e:
```
// https://github.com/rt2zz/redux-persist#persiststorestore-config-callback
persistStore(store, { storage: AsyncStorage }, () => {
```
Note: I added this second parameter `{ storage: AsyncStorage }`.
The README formatting doesn't changed.

doc: persistStore second parameter need to be an object

---

README.md

Example code was giving a wrong option for the config of `persistStore`.
Config there is of type `PersistStoreOptions`, which is:
```
export type PersistorOptions = {
enhancer?: Function,
manualPersist?: boolean
}
```
as seen in https://github.com/rt2zz/redux-persist/blob/master/src/types.js#L32-L35
None, this is a documentation only PR
N/A, this is a documentation only PR

Fix config for persistStore

---

README.md

With https://github.com/rgommezz/react-native-offline/pull/248, the netinfo version has changed to 5.3.x.
Bumping up the version mentioned here to keep the readme upto date.
Please provide enough information so that others can review your pull request:
I was confused by the errors that I got after running yarn. The react-native-offline version changed causing an error in manually linked project.

change: @react-native-community/netinfo docs version

---

README.md
src/utils/checkInternetConnection.ts
test/checkInternetConnection.test.ts

…nection
Fixes #263 
> When I try check my server availability as the first action (example from readme) using checkInternetConnection I can specify only url and timeout. But my server give status 200 only with OPTIONS method, with default HEAD it send 403. We can specify method for provider and context but can't for checkInternetConnection.
Test adapted to additional argument.
Code was linted and prettiered (for `example` folder I reverted changes after prettier).

add: checkInternetConnection, configure method type

---

README.md

The old link was broken.
The old link to the Redux docs was broken. I wanted to fix it so that future readers won't have to search the Redux docs to find the same information. 
I clicked on the link after updating it to make sure it goes to the correct section of the docs. 
I just changed a few characters using GitHub's GUI so the formatting shouldn't have been altered.

docs: fix the link to the async actions redux convention

---

README.md

I use this lib and saw a small typo in Readme. Then, I decided to make the change!
Thanks for this great lib! 😄 
No test needed! Not a code change, just docs.

docs: correct typo with `queue` naming

---

README.md

The motivation of this PR is to improve the docs on [How to intercept and queue actions when the server responds with client (4xx) or server (5xx) errors](https://github.com/rgommezz/react-native-offline#how-to-intercept-and-queue-actions-when-the-server-responds-with-client-4xx-or-server-5xx-errors) with `redux-thunk` example of usage.
Fixes #284

docs: improve example about adding thunks to queue on demand

---

package-lock.json
package.json
src/components/NetworkConnectivity.tsx
src/components/ReduxNetworkProvider.tsx
src/hooks/useIsConnected.ts
src/redux/actionCreators.ts
src/redux/createNetworkMiddleware.ts
src/redux/sagas.ts
src/types.ts
src/utils/checkInternetConnection.ts
test/NetworkConnectivity.test.tsx
test/NetworkConsumer.test.tsx

This PR brings support for react-native-netinfo 6.0 [released in February](https://github.com/react-native-netinfo/react-native-netinfo/releases/tag/v6.0.0), and shipped in Expo since SDK 41.
The main change which impacts this library, and which is a breaking change, is that `isConnected` can be `null` rather than `false` for initial unknown connection state.
This PR follows what did netinfo, by updating types accordingly, and setting `isConnected` to `null` by default. This will request change in app-land, mostly on types and to deal with possible `null` state.
Tested with redux in my app (not with saga that I don't use).
Closes #324

chore: Support react-native-netinfo 6
